[versions]
javalin = "6.7.0"
jackson = "2.18.2"
slf4j = "2.0.16"
junit-jupiter = "5.12.1"

[libraries]
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
javalin-testtools = { module = "io.javalin:javalin-testtools", version.ref = "javalin" }